device: cuda:0
sample_times: 320
elec_channels: 64
patch_size: 160
unmasked_list: [0, 2, 4, 6, 14, 16, 18, 20, 22, 25, 27, 42, 43, 56, 58, 61]
mamba_depth: 2
d_state: 8
decoder_dim: 160
decoder_depth: 2
batch_size: 64
epochs: 800
base_lr: 0.025 #0.015
lr_decay_rate: 0.01
print_freq: 10
eval_freq: 10
num_workers: 8
seed: 2
lr: 0.2